# Generated by Django 2.1.3 on 2018-11-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('Status', models.BooleanField(default=False)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNC_On', models.DateField(blank=True, null=True)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Campaign')),
                ('DNC_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead_On', models.DateField(blank=True, null=True)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Campaign')),
                ('Lead_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Job_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Industry_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=200, null=True)),
                ('Direct_Or_Extension', models.CharField(blank=True, max_length=200, null=True)),
                ('Campaigns', models.ManyToManyField(blank=True, null=True, to='portal.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viewed_On', models.DateField(blank=True, null=True)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Campaign')),
                ('Prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect')),
                ('View_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='Prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect'),
        ),
        migrations.AddField(
            model_name='dnc',
            name='Prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect'),
        ),
    ]
