# Generated by Django 2.1.3 on 2018-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_prospect_released_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='Released_Campaigns',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
