# Generated by Django 2.1.3 on 2018-11-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20181121_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Email',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Info_Updated_Campaign',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Info_Updated_User',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Website',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Company',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Industry_Type',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Job_Title',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Phone',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
