# Generated by Django 2.1.3 on 2018-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20181125_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='Phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
