# Generated by Django 2.0 on 2018-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20181127_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Old_Info',
            field=models.TextField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='To_Be_Updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Update_Company',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Update_Email',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Update_Phone',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='City',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Country',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Direct_Or_Extension',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Emp_Size',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Phone',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Released_Campaigns',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='State',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='Zip_Code',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
