# Generated by Django 2.0 on 2018-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20181130_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Lead_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospect',
            name='View_Count',
            field=models.IntegerField(default=0),
        ),
    ]
